import Link from "next/link";
import { notFound } from "next/navigation";
import { getException, getState } from "@/store/db";
import { buildPathwayStates, resolutionSummary } from "@/engine/dataIntelligence";
import { pathwayByKey, getPathways } from "@/domain/pathways";
import { EvidenceList } from "@/components/EvidenceList";
import { DecisionPanel } from "@/components/DecisionPanel";
import { SeverityBadge, StatusBadge, ConfidenceBadge } from "@/components/Badge";
import { patternLabel, realSince, sinceNow, escalationLabel } from "@/lib/format";
import { currentPlaceId } from "@/lib/session";

export const dynamic = "force-dynamic";

export default async function ExceptionPage(props: { params: Promise<{ id: string }> }) {
  const { id } = await props.params;
  const [exception, state] = await Promise.all([getException(id, await currentPlaceId()), getState()]);
  if (!exception) notFound();

  const patient = state.patients.find((p) => p.id === exception.patientId)!;
  const resolution = resolutionSummary(patient);

  const eventOrgs: Record<string, string> = {};
  for (const it of exception.evidence) {
    const ev = state.events.find((e) => e.id === it.eventId);
    if (ev) eventOrgs[it.eventId] = ev.fromOrgId;
  }

  const pathwayStates = buildPathwayStates(state.patients, state.events, state.now, getPathways()).filter(
    (ps) => ps.patientId === patient.id,
  );

  const task = (state.tasks ?? []).find((t) => t.exceptionId === exception.id && t.status !== "cancelled");

  return (
    <div className="space-y-6">
      <Link href="/queue" className="text-sm font-medium text-teal hover:underline">
        ← Attention queue
      </Link>

      <header className="space-y-3">
        <div className="flex flex-wrap items-center gap-2">
          <SeverityBadge severity={exception.severity} />
          <span className="pill bg-white text-slate-muted ring-1 ring-inset ring-line">
            {patternLabel(exception.pattern)}
          </span>
          <ConfidenceBadge confidence={exception.confidence} />
          <StatusBadge status={exception.status} />
          <span className="pill bg-ink text-white">Priority {exception.score}</span>
        </div>
        <h1 className="text-xl font-bold tracking-tight text-ink">{exception.title}</h1>
        <p className="text-sm text-slate-muted">
          {patient.name} · born {patient.yearOfBirth} · NHS {patient.nhsNumber} (synthetic) · resolved from{" "}
          {resolution.systems} source systems (lowest match confidence {(resolution.lowestConfidence * 100).toFixed(0)}%)
        </p>
        <p className="rounded-lg bg-mist p-3 text-sm text-slate">{patient.summary}</p>
      </header>

      <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        {/* LEFT */}
        <div className="space-y-6">
          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Why this needs attention</h2>
            <p className="mt-2 text-sm leading-relaxed text-slate">{exception.why}</p>
            <p className="mt-2 text-xs text-slate-muted">
              Explanation:{" "}
              {exception.whySource === "deterministic"
                ? "generated by the deterministic engine from the extracted facts."
                : "phrased by a model from the extracted facts; severity, evidence and the recommended action are deterministic."}
            </p>
          </section>

          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Evidence</h2>
            <p className="mt-1 text-xs text-slate-muted">
              Every claim in the explanation traces to one of these source events. Amber markers are expected events
              that are missing.
            </p>
            <div className="mt-3">
              <EvidenceList items={exception.evidence} eventOrgs={eventOrgs} />
            </div>
          </section>

          {pathwayStates.length > 0 && (
            <section className="card p-4">
              <h2 className="text-sm font-bold text-ink">Pathway state</h2>
              <div className="mt-3 space-y-4">
                {pathwayStates.map((ps) => {
                  const def = pathwayByKey(ps.pathway);
                  return (
                    <div key={ps.pathway + ps.triggeredBy}>
                      <p className="text-xs font-semibold text-slate-muted">
                        {def?.label ?? ps.pathway} · opened {sinceNow(ps.triggeredAt)}
                      </p>
                      <ul className="mt-1.5 space-y-1.5">
                        {ps.steps.map((s) => (
                          <li key={s.step.key} className="flex items-center gap-2 text-sm">
                            <span
                              className={`h-2 w-2 shrink-0 rounded-full ${
                                s.satisfied ? "bg-teal-bright" : s.overdueHours > 0 ? "bg-amber" : "bg-line"
                              }`}
                              aria-hidden
                            />
                            <span className={s.satisfied ? "text-slate line-through" : "text-ink"}>
                              {s.step.description}
                            </span>
                            <span className="ml-auto text-xs text-slate-muted">
                              {s.satisfied
                                ? "done"
                                : s.overdueHours > 0
                                  ? `${Math.round(s.overdueHours / 24)}d overdue`
                                  : `due ${sinceNow(s.dueAt)}`}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  );
                })}
              </div>
            </section>
          )}
        </div>

        {/* RIGHT */}
        <div className="space-y-6">
          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Recommended action</h2>
            <p className="mt-2 text-sm text-ink">{exception.recommendedAction}</p>
            <dl className="mt-3 space-y-1 text-sm">
              <div className="flex justify-between gap-3">
                <dt className="text-slate-muted">Owner</dt>
                <dd className="text-right font-medium text-ink">{exception.owner.label}</dd>
              </div>
              <div className="flex justify-between gap-3">
                <dt className="text-slate-muted">Surfaced</dt>
                <dd className="font-medium text-ink">{realSince(exception.createdAt)}</dd>
              </div>
            </dl>
          </section>

          {task && (
            <section className="card border-teal-soft p-4">
              <h2 className="text-sm font-bold text-ink">Task dispatched</h2>
              <p className="mt-2 text-sm text-slate">
                Sent to <span className="font-medium text-ink">{task.owner.label}</span>
                {task.assignee ? ` · ${task.assignee}` : " · team inbox"} ·{" "}
                <span className="font-medium text-ink">{task.status.replace("_", " ")}</span>
                {task.escalationLevel > 0 ? ` · escalated (${escalationLabel(task.escalationLevel)})` : ""}.
              </p>
              <Link href={`/worklist/${task.id}`} className="btn-secondary mt-3">
                Open the task
              </Link>
            </section>
          )}

          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Your decision</h2>
            <div className="mt-3">
              <DecisionPanel
                exceptionId={exception.id}
                status={exception.status}
                recommendedAction={exception.recommendedAction}
              />
            </div>
          </section>

          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Governance checks</h2>
            <ul className="mt-2 space-y-2 text-sm">
              {exception.governance.map((g) => (
                <li key={g.rule} className="flex gap-2">
                  <span
                    className={`pill ${g.outcome === "pass" ? "bg-teal-soft text-teal" : "bg-amber-soft text-amber"}`}
                  >
                    {g.outcome}
                  </span>
                  <span className="text-slate">
                    <span className="font-medium text-ink">{g.rule}</span> — {g.detail}
                  </span>
                </li>
              ))}
            </ul>
          </section>

          <section className="card p-4">
            <h2 className="text-sm font-bold text-ink">Priority score — {exception.score}</h2>
            <ul className="mt-2 space-y-1 text-sm">
              {exception.scoreBreakdown.map((b, i) => (
                <li key={i} className="flex justify-between gap-3">
                  <span className="text-slate">{b.factor}</span>
                  <span className={`font-semibold ${b.points < 0 ? "text-amber" : "text-ink"}`}>
                    {b.points > 0 ? "+" : ""}
                    {b.points}
                  </span>
                </li>
              ))}
            </ul>
            <p className="mt-2 text-xs text-slate-muted">Deterministic and fully itemised — no hidden model in the ranking.</p>
          </section>
        </div>
      </div>

      {exception.decisions.length > 0 && (
        <section className="card p-4">
          <h2 className="text-sm font-bold text-ink">Decision history</h2>
          <ul className="mt-3 space-y-3">
            {exception.decisions.map((d) => (
              <li key={d.id} className="text-sm">
                <div className="flex flex-wrap items-baseline gap-x-2 text-xs text-slate-muted">
                  <span className="pill bg-mist text-slate">{d.kind}</span>
                  <span className="font-medium text-ink">{d.actor}</span>
                  <span>· {realSince(d.at)}</span>
                </div>
                {d.amendedAction && (
                  <p className="mt-1 text-slate">
                    <span className="font-medium text-ink">Amended action:</span> {d.amendedAction}
                  </p>
                )}
                {d.note && <p className="mt-0.5 text-slate">{d.note}</p>}
              </li>
            ))}
          </ul>
          <p className="mt-3 text-xs text-slate-muted">
            The audit trail records what the AI identified, what it recommended, and what you decided — see the{" "}
            <Link href="/audit" className="text-teal hover:underline">
              Audit
            </Link>{" "}
            page.
          </p>
        </section>
      )}
    </div>
  );
}
